---
title: "p8105_hw6"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
nynoaa=read_csv("./data/nynoaadat.zip",col_types = "cDiiidd") %>%
  clean_names()%>%
  separate(date, into = c("year", "month", "day"))

nynoaa=read_csv("./data/nynoaadat.zip",col_types = "cDiiidd") %>%
  separate(date, into = c("year", "month", "day"))

nynoaa%>%
  mutate(tmin = tmin/10, tmax = tmax/10) %>%
  mutate(hover_text=paste("tmax: ", tmax, 'tmin: ', tmin, "Snow: ", snow, sep = "<br>")) %>%
  filter(snow < 100, snow > 0, year>2000) %>%
  plot_ly(x = ~ tmax, y = ~ tmin, hoverinfo = "hover_text", type = "histogram2d", color = ~snow)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```


